In [1]:
from pathlib import Path
import sys
sys.path.insert(0, str(Path.cwd().parent))
from src import constants as cts
from src import helper as hp
import os
import pandas as pd
from dotenv import load_dotenv
load_dotenv()
from google import genai
from src import reviewer, schema
from src.llm import LLMProvider
import jsonlines
from src.providers import penmanshiel_provider as pp
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None) 
pd.set_option("display.width", None)

In [2]:
log_path = list(Path("status_logs").glob("*.csv"))

print(log_path)
log1 = pd.read_csv(log_path[0])
log1.head()

[WindowsPath('status_logs/Status_Logs_Complete_ID_1.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_10.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_11.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_12.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_13.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_14.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_15.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_2.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_4.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_5.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_6.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_7.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_8.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_9.csv')]

C:\Users\admin\AppData\Local\Temp\ipykernel_15480\495428329.py:4: DtypeWarning: Columns (0: Comment) have mixed types. Specify dtype option on import or set low_memory=False.
  log1 = pd.read_csv(log_path[0])

,Timestamp start,Timestamp end,Duration,Status,Code,Message,Comment,Service contract category,IEC category,WT_ID,Global contract category,Custom contract category
0,2016-06-06 17:08:40,2016-06-10 11:28:00,90:19:20,Stop,3500,Grid loss,NaN,External stop (grid) (4),Out of Electrical Specification,1,NaN,NaN
1,2016-06-06 17:08:41,2016-06-06 18:14:07,01:05:26,Warning,3875,Overload transf. fan inlet air,NaN,Warnings (27),NaN,1,NaN,NaN
2,2016-06-06 17:08:41,2016-06-06 18:14:39,01:05:58,Warning,1825,Overload gear bypass filter,NaN,Warnings (27),NaN,1,NaN,NaN
3,2016-06-06 17:08:41,2016-06-06 18:14:07,01:05:26,Warning,3875,Overload transf. fan inlet air,NaN,Warnings (27),NaN,1,NaN,NaN
4,2016-06-06 17:08:41,2016-06-06 18:14:39,01:05:58,Warning,1825,Overload gear bypass filter,NaN,Warnings (27),NaN,1,NaN,NaN

In [ ]:

chunks = hp.load_logfile(list(Path(cts.PATH_STATUS_LOGS).glob("*.csv"))[0],
                                 wt_col=None,
                                 wt_id=None,
                                 detection_ts=pd.to_datetime("2020-11-22 20:00:00"),
                                 ts_cols=["Timestamp start", "Timestamp end"], 
                                 delta_time=pd.Timedelta(days=30)
                                 )

print(len(chunks))
print(chunks)
chunks[0].empty

14
[          Timestamp start       Timestamp end  Duration         Status  Code  \
43648 2020-10-26 06:47:38 2020-10-26 06:49:56  00:02:18           Stop   710
43660 2020-10-28 12:23:47 2020-10-28 13:50:17  01:26:30           Stop    25
43662 2020-10-28 12:24:34 2020-10-28 13:50:17  01:25:43  Informational  6410
43663 2020-10-28 13:25:20 2020-10-28 13:50:23  00:25:03        Warning  2125
43671 2020-10-29 07:44:50 2020-10-29 07:45:38  00:00:48  Informational    10
43679 2020-10-30 20:15:30 2020-10-30 20:16:18  00:00:48  Informational    10
43687 2020-10-30 20:46:12 2020-10-30 20:47:00  00:00:48  Informational    10
43695 2020-10-30 21:36:32 2020-10-30 21:37:20  00:00:48  Informational    10
43703 2020-11-01 21:04:17 2020-11-01 21:05:05  00:00:48  Informational    10
43711 2020-11-02 07:01:09 2020-11-02 07:03:27  00:02:18           Stop   710
43723 2020-11-02 07:42:05 2020-11-02 07:42:52  00:00:47  Informational    10
43731 2020-11-02 08:01:51 2020-11-02 08:02:38  00:00:47  Informational    10
43739 2020-11-02 08:14:14 2020-11-02 08:15:01  00:00:47  Informational    10
43747 2020-11-02 08:33:39 2020-11-02 08:34:27  00:00:48  Informational    10
43755 2020-11-03 01:40:15 2020-11-03 09:47:03  08:06:48  Communication  9997
43756 2020-11-05 17:59:46 2020-11-05 18:00:34  00:00:48  Informational    10
43764 2020-11-05 18:32:15 2020-11-05 18:33:02  00:00:47  Informational    10
43772 2020-11-05 20:19:17 2020-11-05 20:20:05  00:00:48  Informational    10
43780 2020-11-05 20:31:54 2020-11-05 20:32:42  00:00:48  Informational    10
43788 2020-11-05 20:40:09 2020-11-05 20:40:56  00:00:47  Informational    10
43796 2020-11-05 21:07:53 2020-11-05 21:08:40  00:00:47  Informational    10
43804 2020-11-05 21:17:11 2020-11-05 21:17:58  00:00:47  Informational    10
43812 2020-11-05 21:39:19 2020-11-05 21:40:06  00:00:47  Informational    10
43820 2020-11-05 22:29:04 2020-11-05 22:29:51  00:00:47  Informational    10
43828 2020-11-06 00:40:20 2020-11-06 00:41:07  00:00:47  Informational    10
43836 2020-11-06 03:30:34 2020-11-06 03:31:22  00:00:48  Informational    10
43844 2020-11-06 08:27:25 2020-11-06 08:28:13  00:00:48  Informational    10
43852 2020-11-06 09:46:27 2020-11-06 09:47:15  00:00:48  Informational    10
43860 2020-11-06 10:31:09 2020-11-06 10:31:57  00:00:48  Informational    10
43868 2020-11-06 13:18:05 2020-11-06 13:18:53  00:00:48  Informational    10

                              Message Comment  \
43648                    Battery test    <NA>
43660       Manual stop without login    <NA>
43662                      Manual yaw    <NA>
43663            Timeout brake closed    <NA>
43671               Wind < start wind    <NA>
43679               Wind < start wind    <NA>
43687               Wind < start wind    <NA>
43695               Wind < start wind    <NA>
43703               Wind < start wind    <NA>
43711                    Battery test    <NA>
43723               Wind < start wind    <NA>
43731               Wind < start wind    <NA>
43739               Wind < start wind    <NA>
43747               Wind < start wind    <NA>
43755  Data communication unavailable    <NA>
43756               Wind < start wind    <NA>
43764               Wind < start wind    <NA>
43772               Wind < start wind    <NA>
43780               Wind < start wind    <NA>
43788               Wind < start wind    <NA>
43796               Wind < start wind    <NA>
43804               Wind < start wind    <NA>
43812               Wind < start wind    <NA>
43820               Wind < start wind    <NA>
43828               Wind < start wind    <NA>
43836               Wind < start wind    <NA>
43844               Wind < start wind    <NA>
43852               Wind < start wind    <NA>
43860               Wind < start wind    <NA>
43868               Wind < start wind    <NA>

                 Service contract category  \
43648               Operating states  (28)
43660           Manual stop (service)  (9)
43662           Manual stop (service)  (9)
43663                        Warnings (27)
43671  External stop (low wind speed)  (5)
43679  External stop (low wind speed)  (5)
43687  External stop (low wind speed)  (5)
43695  External stop (low wind speed)  (5)
43703  External stop (low wind speed)  (5)
43711               Operating states  (28)
43723  External stop (low wind speed)  (5)
43731  External stop (low wind speed)  (5)
43739  External stop (low wind speed)  (5)
43747  External stop (low wind speed)  (5)
43755                                  NaN
43756  External stop (low wind speed)  (5)
43764  External stop (low wind speed)  (5)
43772  External stop (low wind speed)  (5)
43780  External stop (low wind speed)  (5)
43788  External stop (low wind speed)  (5)
43796  External stop (low wind speed)  (5)
43804  External stop (low wind speed)  (5)
43812  External stop (low wind speed)  (5)
43820  External stop (low wind speed)  (5)
43828  External stop (low wind speed)  (5)
43836  External stop (low wind speed)  (5)
43844  External stop (low wind speed)  (5)
43852  External stop (low wind speed)  (5)
43860  External stop (low wind speed)  (5)
43868  External stop (low wind speed)  (5)

                             IEC category  WT_ID Global contract category  \
43648                   Technical Standby      1                      NaN
43660               Scheduled Maintenance      1                      NaN
43662                    Full Performance      1                      NaN
43663                                 NaN      1                      NaN
43671  Out of Environmental Specification      1                      NaN
43679  Out of Environmental Specification      1                      NaN
43687  Out of Environmental Specification      1                      NaN
43695  Out of Environmental Specification      1                      NaN
43703  Out of Environmental Specification      1                      NaN
43711                   Technical Standby      1                      NaN
43723  Out of Environmental Specification      1                      NaN
43731  Out of Environmental Specification      1                      NaN
43739  Out of Environmental Specification      1                      NaN
43747  Out of Environmental Specification      1                      NaN
43755                                 NaN      1                      NaN
43756  Out of Environmental Specification      1                      NaN
43764  Out of Environmental Specification      1                      NaN
43772  Out of Environmental Specification      1                      NaN
43780  Out of Environmental Specification      1                      NaN
43788  Out of Environmental Specification      1                      NaN
43796  Out of Environmental Specification      1                      NaN
43804  Out of Environmental Specification      1                      NaN
43812  Out of Environmental Specification      1                      NaN
43820  Out of Environmental Specification      1                      NaN
43828  Out of Environmental Specification      1                      NaN
43836  Out of Environmental Specification      1                      NaN
43844  Out of Environmental Specification      1                      NaN
43852  Out of Environmental Specification      1                      NaN
43860  Out of Environmental Specification      1                      NaN
43868  Out of Environmental Specification      1                      NaN

       Custom contract category
43648                       NaN
43660                       NaN
43662                       NaN
43663                       NaN
43671                       NaN
43679                       NaN
43687                       NaN
43695                       NaN
43703                       NaN
43711                       NaN
43723                       NaN
43731                       NaN
43739                       NaN
43747                       NaN
43755                       NaN
43756                       NaN
43764                       NaN
43772                       NaN
43780                       NaN
43788                       NaN
43796                       NaN
43804                       NaN
43812                       NaN
43820                       NaN
43828                       NaN
43836                       NaN
43844                       NaN
43852                       NaN
43860                       NaN
43868                       NaN  ,           Timestamp start       Timestamp end  Duration         Status  Code  \
43876 2020-11-06 17:42:19 2020-11-06 17:43:07  00:00:48  Informational    10
43884 2020-11-06 21:34:54 2020-11-06 21:35:41  00:00:47  Informational    10
43892 2020-11-07 01:10:56 2020-11-07 01:11:44  00:00:48  Informational    10
43900 2020-11-07 05:01:19 2020-11-07 05:02:07  00:00:48  Informational    10
43908 2020-11-07 07:17:51 2020-11-07 07:18:39  00:00:48  Informational    10
43916 2020-11-07 13:24:04 2020-11-07 13:24:51  00:00:47  Informational    10
43924 2020-11-07 15:20:37 2020-11-07 15:21:24  00:00:47  Informational    10
43932 2020-11-07 17:53:03 2020-11-07 17:53:50  00:00:47  Informational    10
43940 2020-11-07 19:11:00 2020-11-07 19:11:48  00:00:48  Informational    10
43948 2020-11-07 21:30:13 2020-11-07 21:31:00  00:00:47  Informational    10
43956 2020-11-07 22:46:15 2020-11-07 22:47:03  00:00:48  Informational    10
43964 2020-11-08 00:02:56 2020-11-08 00:03:44  00:00:48  Informational    10
43972 2020-11-08 00:27:48 2020-11-08 00:28:36  00:00:48  Informational    10
43980 2020-11-08 19:18:07 2020-11-08 19:18:55  00:00:48  Informational    10
43988 2020-11-08 23:50:19 2020-11-08 23:51:07  00:00:48  Informational    10
43996 2020-11-09 02:07:32 2020-11-09 02:08:19  00:00:47  Informational    10
44001 2020-11-09 10:09:28 2020-11-09 10:11:38  00:02:10           Stop   710
44013 2020-11-09 10:45:25 2020-11-09 10:46:13  00:00:48  Informational    10
44021 2020-11-09 14:36:09 2020-11-09 14:36:56  00:00:47  Informational    10
44029 2020-11-09 16:08:04 2020-11-09 16:08:52  00:00:48  Informational    10
44037 2020-11-09 17:13:56 2020-11-09 17:14:44  00:00:48  Informational    10
44045 2020-11-09 18:37:27 2020-11-09 18:38:14  00:00:47  Informational    10
44053 2020-11-09 22:34:34 2020-11-09 22:35:22  00:00:48  Informational    10
44055 2020-11-09 22:34:35 2020-11-09 22:44:36  00:10:01           Stop  5760
44063 2020-11-10 00:43:24 2020-11-10 00:44:11  00:00:47  Informational    10
44065 2020-11-10 00:43:24 2020-11-10 00:44:11  00:00:47  Informational    10
44068 2020-11-10 00:44:11 2020-11-10 02:15:30  01:31:19  Informational     0
44073 2020-11-10 02:15:30 2020-11-10 02:16:17  00:00:47  Informational    10
44075 2020-11-10 02:15:30 2020-11-10 02:16:17  00:00:47  Informational    10
44078 2020-11-10 02:16:17 2020-11-10 04:09:44  01:53:27  Informational     0

                                Message Comment  \
43876                 Wind < start wind    <NA>
43884                 Wind < start wind    <NA>
43892                 Wind < start wind    <NA>
43900                 Wind < start wind    <NA>
43908                 Wind < start wind    <NA>
43916                 Wind < start wind    <NA>
43924                 Wind < start wind    <NA>
43932                 Wind < start wind    <NA>
43940                 Wind < start wind    <NA>
43948                 Wind < start wind    <NA>
43956                 Wind < start wind    <NA>
43964                 Wind < start wind    <NA>
43972                 Wind < start wind    <NA>
43980                 Wind < start wind    <NA>
43988                 Wind < start wind    <NA>
43996                 Wind < start wind    <NA>
44001                      Battery test    <NA>
44013                 Wind < start wind    <NA>
44021                 Wind < start wind    <NA>
44029                 Wind < start wind    <NA>
44037                 Wind < start wind    <NA>
44045                 Wind < start wind    <NA>
44053                 Wind < start wind    <NA>
44055  Hydraulic oil flushing operation    <NA>
44063                 Wind < start wind    <NA>
44065                 Wind < start wind    <NA>
44068                         System OK    <NA>
44073                 Wind < start wind    <NA>
44075                 Wind < start wind    <NA>
44078                         System OK    <NA>

                 Service contract category  \
43876  External stop (low wind speed)  (5)
43884  External stop (low wind speed)  (5)
43892  External stop (low wind speed)  (5)
43900  External stop (low wind speed)  (5)
43908  External stop (low wind speed)  (5)
43916  External stop (low wind speed)  (5)
43924  External stop (low wind speed)  (5)
43932  External stop (low wind speed)  (5)
43940  External stop (low wind speed)  (5)
43948  External stop (low wind speed)  (5)
43956  External stop (low wind speed)  (5)
43964  External stop (low wind speed)  (5)
43972  External stop (low wind speed)  (5)
43980  External stop (low wind speed)  (5)
43988  External stop (low wind speed)  (5)
43996  External stop (low wind speed)  (5)
44001               Operating states  (28)
44013  External stop (low wind speed)  (5)
44021  External stop (low wind speed)  (5)
44029  External stop (low wind speed)  (5)
44037  External stop (low wind speed)  (5)
44045  External stop (low wind speed)  (5)
44053  External stop (low wind speed)  (5)
44055               Operating states  (28)
44063  External stop (low wind speed)  (5)
44065  External stop (low wind speed)  (5)
44068                       System OK (32)
44073  External stop (low wind speed)  (5)
44075  External stop (low wind speed)  (5)
44078                       System OK (32)

                             IEC category  WT_ID Global contract category  \
43876  Out of Environmental Specification      1                      NaN
43884  Out of Environmental Specification      1                      NaN
43892  Out of Environmental Specification      1                      NaN
43900  Out of Environmental Specification      1                      NaN
43908  Out of Environmental Specification      1                      NaN
43916  Out of Environmental Specification      1                      NaN
43924  Out of Environmental Specification      1                      NaN
43932  Out of Environmental Specification      1                      NaN
43940  Out of Environmental Specification      1                      NaN
43948  Out of Environmental Specification      1                      NaN
43956  Out of Environmental Specification      1                      NaN
43964  Out of Environmental Specification      1                      NaN
43972  Out of Environmental Specification      1                      NaN
43980  Out of Environmental Specification      1                      NaN
43988  Out of Environmental Specification      1                      NaN
43996  Out of Environmental Specification      1                      NaN
44001                   Technical Standby      1                      NaN
44013  Out of Environmental Specification      1                      NaN
44021  Out of Environmental Specification      1                      NaN
44029  Out of Environmental Specification      1                      NaN
44037  Out of Environmental Specification      1                      NaN
44045  Out of Environmental Specification      1                      NaN
44053  Out of Environmental Specification      1                      NaN
44055                   Technical Standby      1                      NaN
44063  Out of Environmental Specification      1                      NaN
44065  Out of Environmental Specification      1                      NaN
44068                    Full Performance      1                      NaN
44073  Out of Environmental Specification      1                      NaN
44075  Out of Environmental Specification      1                      NaN
44078                    Full Performance      1                      NaN

       Custom contract category
43876                       NaN
43884                       NaN
43892                       NaN
43900                       NaN
43908                       NaN
43916                       NaN
43924                       NaN
43932                       NaN
43940                       NaN
43948                       NaN
43956                       NaN
43964                       NaN
43972                       NaN
43980                       NaN
43988                       NaN
43996                       NaN
44001                       NaN
44013                       NaN
44021                       NaN
44029                       NaN
44037                       NaN
44045                       NaN
44053                       NaN
44055                       NaN
44063                       NaN
44065                       NaN
44068                       NaN
44073                       NaN
44075                       NaN
44078                       NaN  ,           Timestamp start       Timestamp end  Duration         Status  Code  \
44083 2020-11-10 04:09:44 2020-11-10 04:10:32  00:00:48  Informational    10
44085 2020-11-10 04:09:44 2020-11-10 04:10:32  00:00:48  Informational    10
44093 2020-11-10 15:10:20 2020-11-10 23:02:11  07:51:51  Communication  9997
44094 2020-11-14 15:40:20 2020-11-14 23:28:11  07:47:51  Communication  9997
44095 2020-11-17 12:34:46 2020-11-17 12:36:32  00:01:46           Stop   707
44100 2020-11-17 12:39:06 2020-11-17 12:41:13  00:02:07           Stop   710
44112 2020-11-18 03:55:08 2020-11-18 04:11:30  00:16:22           Stop    64
44120 2020-11-18 04:17:39 2020-11-18 04:36:48  00:19:09           Stop    64
44128 2020-11-19 20:25:06 2020-11-19 20:25:53  00:00:47  Informational    10
44136 2020-11-19 21:10:17 2020-11-19 21:11:04  00:00:47  Informational    10
44144 2020-11-19 22:35:16 2020-11-19 22:36:03  00:00:47  Informational    10
44152 2020-11-24 21:35:00 2020-11-24 21:35:47  00:00:47  Informational    10
44160 2020-11-25 04:46:54 2020-11-25 04:47:42  00:00:48  Informational    10
44165 2020-11-25 06:31:39 2020-11-25 06:33:49  00:02:10           Stop   710
44177 2020-11-25 07:19:47 2020-11-25 07:20:35  00:00:48  Informational    10
44185 2020-11-25 10:32:19 2020-11-25 10:33:06  00:00:47  Informational    10
44193 2020-11-25 12:32:28 2020-11-25 12:33:15  00:00:47  Informational    10
44201 2020-11-25 13:23:22 2020-11-25 13:24:09  00:00:47  Informational    10
44209 2020-11-25 14:52:25 2020-11-25 14:53:13  00:00:48  Informational    10
44217 2020-11-25 21:13:43 2020-11-25 21:14:31  00:00:48  Informational    10
44225 2020-11-26 04:39:22 2020-11-26 04:40:10  00:00:48  Informational    10
44233 2020-11-26 05:09:42 2020-11-26 05:10:29  00:00:47  Informational    10
44241 2020-11-26 06:18:06 2020-11-26 06:18:53  00:00:47  Informational    10
44249 2020-11-26 07:15:25 2020-11-26 07:16:12  00:00:47  Informational    10
44257 2020-11-26 09:44:37 2020-11-26 09:45:25  00:00:48  Informational    10
44265 2020-11-26 13:30:59 2020-11-26 13:31:46  00:00:47  Informational    10
44273 2020-11-26 17:35:02 2020-11-26 17:35:49  00:00:47  Informational    10
44281 2020-11-27 00:43:17 2020-11-27 00:44:05  00:00:48  Informational    10
44289 2020-11-27 03:58:50 2020-11-27 03:59:38  00:00:48  Informational    10
44297 2020-11-27 05:41:21 2020-11-27 05:42:09  00:00:48  Informational    10

                              Message Comment  \
44083               Wind < start wind    <NA>
44085               Wind < start wind    <NA>
44093  Data communication unavailable    <NA>
44094  Data communication unavailable    <NA>
44095               Stop battery test    <NA>
44100                    Battery test    <NA>
44112                 Max. wind speed    <NA>
44120                 Max. wind speed    <NA>
44128               Wind < start wind    <NA>
44136               Wind < start wind    <NA>
44144               Wind < start wind    <NA>
44152               Wind < start wind    <NA>

False

In [ ]:
from src import constants as cts
print(list(Path(cts.PATH_STATUS_LOGS).glob("*.csv"))[0])

C:\Users\admin\Programming\llms\llm-wind-turbine-status-log-review\examples\status_logs\Status_Logs_Complete_ID_1.csv

In [ ]:
from src import prompt as p

format = p.format_chunk_logs(chunk_log=chunks[0], columns=cts.LOG_COLS)

print(format)

df_index=43648;Timestamp start=2020-10-26 06:47:38;Timestamp end=2020-10-26 06:49:56;WT_ID=1;Status=Stop;Code=710;Message=Battery test;Comment=<NA>
df_index=43660;Timestamp start=2020-10-28 12:23:47;Timestamp end=2020-10-28 13:50:17;WT_ID=1;Status=Stop;Code=25;Message=Manual stop without login;Comment=<NA>
df_index=43662;Timestamp start=2020-10-28 12:24:34;Timestamp end=2020-10-28 13:50:17;WT_ID=1;Status=Informational;Code=6410;Message=Manual yaw;Comment=<NA>
df_index=43663;Timestamp start=2020-10-28 13:25:20;Timestamp end=2020-10-28 13:50:23;WT_ID=1;Status=Warning;Code=2125;Message=Timeout brake closed;Comment=<NA>
df_index=43671;Timestamp start=2020-10-29 07:44:50;Timestamp end=2020-10-29 07:45:38;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43679;Timestamp start=2020-10-30 20:15:30;Timestamp end=2020-10-30 20:16:18;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43687;Timestamp start=2020-10-30 20:46:12;Timestamp end=2020-10-30 20:47:00;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43695;Timestamp start=2020-10-30 21:36:32;Timestamp end=2020-10-30 21:37:20;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43703;Timestamp start=2020-11-01 21:04:17;Timestamp end=2020-11-01 21:05:05;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43711;Timestamp start=2020-11-02 07:01:09;Timestamp end=2020-11-02 07:03:27;WT_ID=1;Status=Stop;Code=710;Message=Battery test;Comment=<NA>
df_index=43723;Timestamp start=2020-11-02 07:42:05;Timestamp end=2020-11-02 07:42:52;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43731;Timestamp start=2020-11-02 08:01:51;Timestamp end=2020-11-02 08:02:38;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43739;Timestamp start=2020-11-02 08:14:14;Timestamp end=2020-11-02 08:15:01;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43747;Timestamp start=2020-11-02 08:33:39;Timestamp end=2020-11-02 08:34:27;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43755;Timestamp start=2020-11-03 01:40:15;Timestamp end=2020-11-03 09:47:03;WT_ID=1;Status=Communication;Code=9997;Message=Data communication unavailable;Comment=<NA>
df_index=43756;Timestamp start=2020-11-05 17:59:46;Timestamp end=2020-11-05 18:00:34;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43764;Timestamp start=2020-11-05 18:32:15;Timestamp end=2020-11-05 18:33:02;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43772;Timestamp start=2020-11-05 20:19:17;Timestamp end=2020-11-05 20:20:05;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43780;Timestamp start=2020-11-05 20:31:54;Timestamp end=2020-11-05 20:32:42;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43788;Timestamp start=2020-11-05 20:40:09;Timestamp end=2020-11-05 20:40:56;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43796;Timestamp start=2020-11-05 21:07:53;Timestamp end=2020-11-05 21:08:40;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43804;Timestamp start=2020-11-05 21:17:11;Timestamp end=2020-11-05 21:17:58;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43812;Timestamp start=2020-11-05 21:39:19;Timestamp end=2020-11-05 21:40:06;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43820;Timestamp start=2020-11-05 22:29:04;Timestamp end=2020-11-05 22:29:51;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43828;Timestamp start=2020-11-06 00:40:20;Timestamp end=2020-11-06 00:41:07;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43836;Timestamp start=2020-11-06 03:30:34;Timestamp end=2020-11-06 03:31:22;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43844;Timestamp start=2020-11-06 08:27:25;Timestamp end=2020-11-06 08:28:13;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43852;Timestamp start=2020-11-06 09:46:27;Timestamp end=2020-11-06 09:47:15;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43860;Timestamp start=2020-11-06 10:31:09;Timestamp end=2020-11-06 10:31:57;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>
df_index=43868;Timestamp start=2020-11-06 13:18:05;Timestamp end=2020-11-06 13:18:53;WT_ID=1;Status=Informational;Code=10;Message=Wind < start wind;Comment=<NA>

In [ ]:
# from src import llm

# raw_res = llm.call_ollama(
#     prompt=prompt,
#     model="llama3.2:3b",
#     temperature=0.0,
# )

# print(raw_res)

In [ ]:
client = genai.Client()

for model in client.models.list():
    print(model.name)
    print("supported actions:", model.supported_actions)
    print()

models/gemini-2.5-flash
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.5-pro
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.0-flash
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.0-flash-001
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.0-flash-lite-001
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.0-flash-lite
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.5-flash-preview-tts
supported actions: ['countTokens', 'generateContent']

models/gemini-2.5-pro-preview-tts
supported actions: ['countTokens', 'generateContent', 'batchGenerateContent']

models/gemma-4-26b-a4b-it
supported actions: ['generateContent', 'countTokens']

models/gemma-4-31b-it
supported actions: ['generateContent', 'countTokens']

models/gemini-flash-latest
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-flash-lite-latest
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-pro-latest
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.5-flash-lite
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.5-flash-image
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-3-pro-preview
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3-flash-preview
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3.1-pro-preview
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3.1-pro-preview-customtools
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3.1-flash-lite-preview
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3.1-flash-lite
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3-pro-image-preview
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-3-pro-image
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/nano-banana-pro-preview
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-3.1-flash-image-preview
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-3.1-flash-image
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-3.5-flash
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/lyria-3-clip-preview
supported actions: ['generateContent', 'countTokens']

models/lyria-3-pro-preview
supported actions: ['generateContent', 'countTokens']

models/gemini-3.1-flash-tts-preview
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-robotics-er-1.5-preview
supported actions: ['generateContent', 'countTokens']

models/gemini-robotics-er-1.6-preview
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.5-computer-use-preview-10-2025
supported actions: ['generateContent', 'countTokens']

models/antigravity-preview-05-2026
supported actions: ['generateContent', 'countTokens']

models/deep-research-max-preview-04-2026
supported actions: ['generateContent', 'countTokens']

models/deep-research-preview-04-2026
supported actions: ['generateContent', 'countTokens']

models/deep-research-pro-preview-12-2025
supported actions: ['generateContent', 'countTokens']

models/gemini-embedding-001
supported actions: ['embedContent', 'countTextTokens', 'countTokens', 'asyncBatchEmbedContent']

models/gemini-embedding-2-preview
supported actions: ['embedContent', 'countTextTokens', 'countTokens', 'asyncBatchEmbedContent']

models/gemini-embedding-2
supported actions: ['embedContent', 'countTextTokens', 'countTokens', 'asyncBatchEmbedContent']

models/aqa
supported actions: ['generateAnswer']

models/imagen-4.0-generate-001
supported actions: ['predict']

models/imagen-4.0-ultra-generate-001
supported actions: ['predict']

models/imagen-4.0-fast-generate-001
supported actions: ['predict']

models/veo-2.0-generate-001
supported actions: ['predictLongRunning']

models/veo-3.0-generate-001
supported actions: ['predictLongRunning']

models/veo-3.0-fast-generate-001
supported actions: ['predictLongRunning']

models/veo-3.1-generate-preview
supported actions: ['predictLongRunning']

models/veo-3.1-fast-generate-preview
supported actions: ['predictLongRunning']

models/veo-3.1-lite-generate-preview
supported actions: ['predictLongRunning']

models/gemini-2.5-flash-native-audio-latest
supported actions: ['countTokens', 'bidiGenerateContent']

models/gemini-2.5-flash-native-audio-preview-09-2025
supported actions: ['countTokens', 'bidiGenerateContent']

models/gemini-2.5-flash-native-audio-preview-12-2025
supported actions: ['countTokens', 'bidiGenerateContent']

models/gemini-3.1-flash-live-preview
supported actions: ['bidiGenerateContent']

models/gemini-3.5-live-translate-preview
supported actions: ['bidiGenerateContent']

In [ ]:
#test = dets.iloc[:5]
test = pp.penmanshielProvider()._load_detections()

outputs = reviewer.deep_search(
    detections=test,
    log_path=log_path,
    provider=LLMProvider.GEMINI,
    model="gemini-2.5-flash")

Inspecting Detections: 1it [01:13, 73.80s/it]

In [12]:
row = dets.iloc[0]
print(type(row))
df = pd.DataFrame(row)
df = df.transpose()
df.shape
print(type(df))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [4]:
try:
    if outputs:
        result_no_logs = pd.DataFrame([output.model_dump() for output in outputs if not output.relevant_logs])

        result_no_logs.head()
except:
    pass

In [5]:
result = pd.DataFrame([output.model_dump() for output in outputs])

result.head(50)

,wt_id,detection_id,detection_index,detection_ts,relevant_signal,anomaly_description_reasoning,relevant_logs,overall_assessment,overall_reasoning
0,2,0,69,2021-01-21 12:30:00,Generator bearing front temperature (°C),"The generator bearing front temperature shows a significant increase, indicating a potential overheating issue.","[{'log_index': '64234', 'log_start_ts': '2021-01-18 11:04:27', 'log_end_ts': '2021-01-18 17:06:53', 'reasoning': 'Overload warnings for generator fans indicate a problem with the generator's cooling system, which can directly lead to increased generator bearing temperatures.'}, {'log_index': '64235', 'log_start_ts': '2021-01-18 11:04:27', 'log_end_ts': '2021-01-18 17:06:53', 'reasoning': 'Overload warnings for generator fans indicate a problem with the generator's cooling system, which can directly lead to increased generator bearing temperatures.'}, {'log_index': '64236', 'log_start_ts': '2021-01-18 11:04:27', 'log_end_ts': '2021-01-18 17:06:52', 'reasoning': 'Overload warnings for generator fans indicate a problem with the generator's cooling system, which can directly lead to increased generator bearing temperatures.'}]",possibly_undocumented_anomaly,"The anomaly statistics show a clear deviation in generator bearing front temperature, but no relevant status logs are found to document this event."

In [ ]:
df = reviewer.read_jsonl(cts.PATH_OUTPUT / cts.FN_OUTPUT)

reviewer.view_on_col(df.iloc[0],"anomaly_description_reasoning")

The 'Generator bearing front temperature (°C)' signal shows a significant increase, with the value at detection (66.11 °C) being 25.67 °C higher than the baseline mean (40.44 °C), resulting in a high Z-score of 5.82. This indicates a substantial deviation from normal operating conditions for the generator bearing temperature.

In [ ]:
df.head()

,wt_id,detection_id,detection_ts,relevant_signal,anomaly_description_reasoning,relevant_logs,overall_assessment,overall_reasoning,n_relevant_logs
0,2,0,2021-01-21 12:30:00,Generator bearing front temperature (°C),"The 'Generator bearing front temperature (°C)' signal shows a significant increase, with the value at detection (66.11 °C) being 25.67 °C higher than the baseline mean (40.44 °C), resulting in a high Z-score of 5.82. This indicates a substantial deviation from normal operating conditions for the generator bearing temperature.","[{'log_index': '64234', 'log_start_ts': '2021-01-18 11:04:27', 'log_end_ts': '2021-01-18 17:06:53', 'reasoning': 'This log indicates an overload condition for generator fan 1. Generator fans are critical for cooling the generator, and an overload suggests a malfunction or reduced efficiency in the cooling system. This directly impacts the generator's thermal management and can lead to increased bearing temperatures. The log occurred three days before the detection, making it temporally relevant to the developing temperature anomaly.'}, {'log_index': '64235', 'log_start_ts': '2021-01-18 11:04:27', 'log_end_ts': '2021-01-18 17:06:53', 'reasoning': 'Similar to log 64234, this log indicates an overload condition for generator fan 2. A problem with any of the generator cooling fans can lead to insufficient heat dissipation, directly contributing to elevated generator bearing temperatures. This log is temporally relevant, occurring shortly before the detected temperature increase.'}, {'log_index': '64236', 'log_start_ts': '2021-01-18 11:04:27', 'log_end_ts': '2021-01-18 17:06:52', 'reasoning': 'This log indicates an overload condition for generator fan 3. The simultaneous overload warnings for multiple generator fans (1, 2, and 3) strongly suggest a systemic issue with the generator's cooling system. This directly correlates with the observed increase in generator bearing front temperature, providing concrete evidence for a potential cause of overheating. The timing is also relevant, preceding the anomaly detection.'}, {'log_index': '64243', 'log_start_ts': '2021-01-18 11:58:17', 'log_end_ts': '2021-01-18 17:01:45', 'reasoning': 'The 'Timeout brake closed' warning indicates a potential issue with the braking system. The brake is typically located on the high-speed shaft, physically close to the generator. A malfunction in the brake could lead to abnormal mechanical stress, friction, or heat generation that could transfer to and affect the generator bearings, contributing to increased temperature. This event occurred approximately three days before the detection.'}, {'log_index': '64309', 'log_start_ts': '2021-01-19 15:15:42', 'log_end_ts': '2021-01-19 16:02:25', 'reasoning': 'A 'High rotor speed nacelle' stop indicates that the turbine experienced excessive rotor speeds. High rotor speed directly translates to high generator speed. Such events can impose significant mechanical and thermal stress on the generator bearings due to increased rotational friction and load, potentially leading to an increase in their operating temperature. This event occurred two days before the detection of elevated generator bearing temperature.'}]",possibly_undocumented_anomaly,"The anomaly detection for the generator bearing front temperature is statistically significant, indicating a clear deviation from the baseline. However, the provided status logs do not contain any concrete documented evidence related to the generator, its bearings, or any directly associated fault mechanisms. The logs primarily consist of generic operational messages (e.g., 'Wind < start wind', 'Battery test', 'Max. wind speed') or events related to other subsystems ('Cable autounwind'), and they all predate the detection timestamp by several weeks, making them temporally irrelevant to the observed anomaly.",5
1,15,1,2022-09-04 04:10:00,Rotor bearing temp (°C),"The rotor bearing temperature shows a significant and sustained increase, with the mean temperature during the event window (36.07 °C) being 7.86 °C higher than the baseline mean (28.21 °C). The temperature at the detection timestamp (35.47 °C) is 7.27 °C above the baseline mean, resulting in a Z-score of 3.11. The Z-shift of 3.37 further indicates a statistically significant upward shift in the temperature distribution, suggesting a potential issue with the rotor bearing.",[],possibly_undocumented_anomaly,"The anomaly statistics clearly indicate a significant and sustained increase in rotor bearing temperature, suggesting a meaningful anomaly. However, none of the provided status logs offer concrete documented evidence directly related to the rotor bearing, its temperature, or any closely associated components or fault mechanisms. The logs primarily consist of 'Wind < start wind' events, a 'Battery test', and a 'Rotor rotation direction nacelle' stop, none of which are directly or indirectly linked to a rotor bearing temperature increase according to the strict evidence rules. Therefore, the anomaly appears to be undocumented by the available status logs.",0
2,14,2,2021-06-25 09:00:00,Generator bearing front temperature (°C),"The generator bearing front temperature shows a statistically significant increase. The value at the detection timestamp is 43.0 °C, which is 5.64 °C higher than the baseline mean (37.36 °C), corresponding to a Z-score of 1.69. The mean temperature during the event window (44.64 °C) is 7.28 °C higher than the baseline mean, with a Z-shift of 2.18. This indicates a sustained elevation in temperature, suggesting a potential issue with the generator bearing.",[],possibly_undocumented_anomaly,"The anomaly detection clearly indicates a statistically significant and sustained increase in the generator bearing front temperature. However, none of the provided status logs are relevant to this specific anomaly. All logs are from a period more than three weeks prior to the detection timestamp (2021-06-25) and consist primarily of generic operational events such as 'Wind < start wind', 'Battery test', 'Externally stopped', 'P output externally reduced', 'Hydraulic oil flushing operation', and 'Cable autounwind'. These logs do not provide any concrete, temporally relevant evidence related to the generator, its bearings, or temperature issues. Therefore, the anomaly is considered possibly undocumented by the available logs.",0
3,14,3,2021-06-25 09:00:00,Rotor bearing temp (°C),"The rotor bearing temperature shows a sustained increase, with the value at the detection timestamp (31.61 °C) being significantly higher than the baseline mean (26.84 °C). The z-score of 1.92 and a mean shift z-score of 2.12 indicate a statistically significant deviation from normal operating conditions for this signal.",[],possibly_undocumented_anomaly,"The anomaly statistics clearly indicate a sustained increase in the rotor bearing temperature. However, all provided status logs occurred weeks before the detection timestamp (detection on 2021-06-25, logs up to 2021-06-04). Due to this significant temporal distance, none of the logs can be considered concrete documented evidence related to this specific temperature anomaly. Therefore, it is assessed as a possibly undocumented anomaly.",0
4,12,4,2020-10-10 19:00:00,Generator bearing front temperature (°C),"The anomaly detection highlights a significant increase in the 'Generator bearing front temperature (°C)'. At the detection timestamp, the temperature reached 68.94 °C, which is 31.04 °C higher than the baseline mean of 37.9 °C. This deviation results in a high Z-score of 6.67, indicating a strong and abnormal heating of the generator's front bearing. Potential causes for such an increase include increased friction, lubrication issues, or a problem with the generator's cooling system.","[{'log_index': '7863', 'log_start_ts': '2020-09-16 10:14:32', 'log_end_ts': '2020-09-16 10:14:38', 'reasoning': 'This log indicates 'Manual operation generator fan 1'. The generator fan is a critical component of the generator's cooling system. Any issue or intervention with the cooling system can directly affect the generator's operating temperature, including its bearings. Insufficient or improper cooling due to fan issues could lead to increased generator bearing temperatures over time. Although this event occurred approximately 24 days before the detection, problems with cooling can have a delayed or cumulative effect on bearing health and temperature, making this log relevant to the observed anomaly.'}, {'log_index': '8318', 'log_start_ts': '2020-10-10 15:44:50', 'log_end_ts': '2020-10-10 15:59:17', 'reasoning': 'This log indicates a 'Gearbox warm-up stage' occurring approximately 3 hours before the generator bearing temperature anomaly. The gearbox is mechanically coupled to the generator, and its thermal state and operational phases can influence the generator's thermal conditions, especially during startup or specific operational sequences after a long stop (as indicated by earlier 'Park master stop' logs).'}, {'log_index': '8321', 'log_start_ts': '2020-10-10 16:25:12', 'log_end_ts': '2020-10-10 16:27:01', 'reasoning': 'This log reports 'Missing gear oil (high rpm)' in the gearbox, occurring approximately 2.5 hours before the generator bearing temperature anomaly. The gearbox is a physically and mechanically coupled component to the generator. A lack of lubrication in the gearbox can lead to increased friction and heat generation within the drivetrain, which can directly transfer to or influence the thermal conditions of the generator bearings, causing elevated temperatures.'}, {'log_index': '33781', 'log_start_ts': '2020-09-16 10:14:32', 'log_end_ts': '2020-09-16 10:14:38', 'reasoning': 'This log indicates 'Manual operation generator fan 1'. The generator fan is directly responsible for cooling the generator, which includes its bearings. Manual operation could suggest a prior issue, inspection, or maintenance activity related to the generator's cooling system, which is directly relevant to generator bearing temperature anomalies.'}, {'log_index': '33782', 'log_start_ts': '2020-09-16 10:14:38', 'log_end_ts': '2020-09-16 10:14:43', 'reasoning': 'This log indicates 'Manual operation fan gear'. This likely refers to a cooling fan for the gearbox. The gearbox is mechanically and thermally coupled to the generator. Issues with gearbox cooling or maintenance activities on its cooling system could indirectly affect the thermal load on the generator and its bearings.'}, {'log_index': '33783', 'log_start_ts': '2020-09-16 10:14:43', 'log_end_ts': '2020-09-16 10:14:47', 'reasoning': 'This log indicates 'Manual operation gear oil pump'. The gear oil pump is crucial for lubricating and cooling the gearbox. Proper lubrication and cooling of the gearbox are essential to prevent overheating, which can transfer heat to the generator and its bearings due to their mechanical coupling. Manual operation suggests an intervention or check related to this critical system.'}, {'log_index': '34239', 'log_start_ts': '2020-10-10 16:25:12', 'log_end_ts': '2020-10-10 16:27:01', 'reasoning': 'This log indicates 'Missing gear oil (high rpm)' in the gearbox, which is mechanically coupled to the generator. A lubrication issue in the gearbox would lead to increased friction and heat generation. This heat can be transferred to the generator and its bearings, directly contributing to or exacerbating the elevated generator bearing front temperature detected less than three hours later. This provides concrete evidence of a related issue in a physically and operationally dependent component.'}]",documented_relevant_event,"The anomaly statistics clearly show a significant and sustained increase in the generator bearing front temperature. The status log indicating 'Manual operation generator fan 1' provides concrete documented evidence related to the generator's cooling system, which is directly responsible for managing the generator's thermal conditions and, consequently, its bearing temperatures. While the log is from about 24 days prior to the detection, issues with cooling can lead to progressive wear or overheating that manifests as a temperature anomaly later on. Therefore, this log is considered relevant evidence.",7

In [ ]:
import requests
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor
from glob import glob
from zipfile import ZipFile
import os
from joblib import Parallel, delayed
import warnings


urls = [
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2016_WT01-10_3107.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2016_WT11-15_3107.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2017_WT01-10_3114.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2017_WT11-15_3115.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2018_WT01-10_3113.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2018_WT11-15_3116.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2019_WT01-10_3112.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2019_WT11-15_3117.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2020_WT01-10_3109.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2020_WT11-15_3118.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2021_WT01-10_4460.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2021_WT11-15_4461.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2022_WT01-10_4462.zip?download=1",
    "https://zenodo.org/records/8253010/files/Penmanshiel_SCADA_2022_WT11-15_4463.zip?download=1",
]

def filename_from_url(url) -> str:
    fn = url.split("/")[-1].split("?")[0]
    return fn

def download_file(url):
    response = requests.get(url, stream=True)
    fn = filename_from_url(url)
    print(f"Downloading: {fn}...")
    with open(cts.PATH_SIGNALS/fn, mode="wb") as file:
        for chunk in response.iter_content(chunk_size=100*1024):
            file.write(chunk)
    print(f"Download: {fn} [finished]")
    
def download_penmanshiel(urls: list[str]):
    Path(cts.PATH_SIGNALS).mkdir(parents=True, exist_ok=True)
    with ThreadPoolExecutor(max_workers=8) as ex:
        ex.map(lambda url: download_file(url), urls)

def extract_all_zips(path: Path):
    def _extract_zip(file:Path) -> None:
        with ZipFile(file, mode="r") as zip_file:
            items = zip_file.namelist()
            items = [item for item in items if item.startswith("Turbine")]
            zip_file.extractall(file.parent, members=items)
            
    zip_files = list(path.glob("*.zip"))
    
    list(tqdm(
        map(_extract_zip, zip_files),
        total=len(zip_files),
        desc="Unpacking ZIP files",
        unit="File",
    ))


COLUMNS_TO_SELECT = [
    'Ambient temperature (converter) (°C)',
    'Date and time',
    'Drive train acceleration (mm/ss)',
    'Gear oil inlet pressure (bar)',
    'Gear oil pump pressure (bar)',
    'Gearbox speed (RPM)',
    'Generator bearing front temperature (°C)',
    'Generator bearing rear temperature (°C)',
    'Generator RPM (RPM)',
    'Hub temperature (°C)',
    'Motor current axis 1 (A)',
    'Motor current axis 2 (A)',
    'Motor current axis 3 (A)',
    'Nacelle ambient temperature (°C)',
    'Nacelle position (°)',
    'Nacelle temperature (°C)',
    'Power (kW)',
    'Rotor bearing temp (°C)',
    'Rotor speed (RPM)',
    'Stator temperature 1 (°C)',
    'Temp. top box (°C)',
    'Temperature motor axis 1 (°C)',
    'Temperature motor axis 2 (°C)',
    'Temperature motor axis 3 (°C)',
    'Vane position 1+2 (°)',
    'Wind direction (°)',
    'Wind speed (m/s)',
    "Blade angle (pitch position) A (°)",
    "Blade angle (pitch position) B (°)",
    "Blade angle (pitch position) C (°)",
    "Front bearing temperature (°C)",
    "Gear oil inlet temperature (°C)",
    "Gear oil temperature (°C)",
    "Rear bearing temperature (°C)",
    "Tower Acceleration X (mm/ss)",
    "Tower Acceleration y (mm/ss)",
    "Transformer cell temperature (°C)",
    "Transformer temperature (°C)",
    "Yaw bearing angle (°)",
]

def cleanup_zip_files():
    zips = list(cts.PATH_SIGNALS.glob("*.zip"))
    [os.remove(file) for file in tqdm(zips, desc="Cleaning up ZIP files")]

def preprocessing_merge_files(path:Path):
    wts = [1,2,4,5,6,7,8,9,10,11,12,13,14,15]
    def _clean_csv(fn:Path)-> pd.DataFrame:
        df = pd.read_csv(fn, skiprows=9)
        df.columns = [col.lstrip("#").strip() for col in df.columns]
        df = df.loc[:, COLUMNS_TO_SELECT]
        return df
    
    def _process_wt(wt:int):
        files = list(cts.PATH_SIGNALS.glob(f"Turbine_Data*_0{wt}_*" if wt < 10 else f"Turbine_Data*_{wt}_*" ))
        dfs = list(map(_clean_csv, files))
        df = pd.concat(dfs, axis=0)
        df[cts.WT_ID] = wt
        df = df.loc[:, [cts.WT_ID] + COLUMNS_TO_SELECT]
        df.rename(columns={"Tower Acceleration y (mm/ss)": "Tower Acceleration Y (mm/ss)"}, inplace=True)
        df[cts.DET_TS_COL] = pd.to_datetime(df[cts.DET_TS_COL], errors="coerce")
        df.sort_values(by=[cts.DET_TS_COL], ascending=True)
        df.to_csv(cts.PATH_SIGNALS/f"WT_{wt}.csv", index=False)
        [os.remove(file) for file in files]
        
    with warnings.catch_warnings():
        warnings.simplefilter(action="ignore", category=pd.errors.PerformanceWarning)
        Parallel(n_jobs=8, backend="threading")(
            delayed(_process_wt)(wt) for wt in  tqdm(wts, desc="Process Files", unit="File")
        )

def penmanshiel_setup():
    
    download_penmanshiel(urls)

In [ ]:

download_penmanshiel(urls[:3])

Downloading: Penmanshiel_SCADA_2017_WT01-10_3114.zip...Downloading: Penmanshiel_SCADA_2016_WT11-15_3107.zip...

Downloading: Penmanshiel_SCADA_2016_WT01-10_3107.zip...
Download: Penmanshiel_SCADA_2016_WT11-15_3107.zip [finished]
Download: Penmanshiel_SCADA_2016_WT01-10_3107.zip [finished]
Download: Penmanshiel_SCADA_2017_WT01-10_3114.zip [finished]

In [ ]:
extract_all_zips(cts.PATH_SIGNALS)

Unpacking ZIP files: 100%|██████████| 3/3 [00:12<00:00,  4.32s/File]

In [ ]:
preprocessing_merge_files(cts.PATH_SIGNALS)

Process Files: 100%|██████████| 14/14 [00:00<00:00, 1998.78File/s]

In [ ]:
files = list(cts.PATH_SIGNALS.glob(f"Turbine_Data*_0{1}_*" if 1 < 10 else f"Turbine_Data*_{11}_*" ))
print(files)

[WindowsPath('C:/Users/admin/Programming/llms/llm-wind-turbine-status-log-review/examples/raw_signals/Turbine_Data_Penmanshiel_01_2016-06-06_-_2017-01-01_1042.csv'), WindowsPath('C:/Users/admin/Programming/llms/llm-wind-turbine-status-log-review/examples/raw_signals/Turbine_Data_Penmanshiel_01_2017-01-01_-_2018-01-01_1042.csv')]

In [6]:
import src.signal_context as sc
import src.providers.penmanshiel_provider as pp
import pprint
from typing import Any
scontext = sc.compute_signal_context("2", "2021-01-21 12:30:00","Generator bearing front temperature (°C)" ,pp.penmanshielProvider())
scada_df= pp.penmanshielProvider().get_scada("2")
det = pp.penmanshielProvider().get_detection("2", "2021-01-21 12:30:00","Generator bearing front temperature (°C)")
window = pp.penmanshielProvider().get_signal_window(scada_df, det)
df = scontext["signal_window"]

In [35]:
def get_all_detections() -> pd.DataFrame:
    file = list(cts.PATH_DETECTIONS.glob("*.csv"))[0]
    dets_df = pd.read_csv(file)
    dets_df = dets_df.sort_values(by=["z_shift"], ascending=False)
    dets_df = dets_df.reset_index()
    
    cols = list(dets_df.columns)
    print(cols)
    def to_dict(idx,row) -> dict[str,Any]:
        a_dict = {}
        a_dict["detection_id"] = idx
        for col in cols:
            a_dict[col] = row[col]
        
        return a_dict
    
    dets = [to_dict(idx,row) for idx, row in dets_df.iterrows()]
    
    return dets

In [36]:
dets = get_all_detections()

['index', 'WT_ID', 're_at_ts', 'Date and time', 'signal_name', 'window_start', 'window_end', 'wind_center', 'n_baseline', 'mean_baseline', 'std_baseline', 'mean_event', 'std_event', 'value_at_ts', 'delta_at_ts', 'z_at_ts', 'delta_mean', 'z_shift']

In [ ]:


    

pprint.pp(dets)

[{'detection_id': 0,
  'index': 69,
  'WT_ID': 2,
  're_at_ts': 0.6844033002853394,
  'Date and time': '2021-01-21 12:30:00',
  'signal_name': 'Generator bearing front temperature (°C)',
  'window_start': '2021-01-11 02:10:00',
  'window_end': '2021-01-26 15:10:00',
  'wind_center': 19.5,
  'n_baseline': 231,
  'mean_baseline': 40.43692257375378,
  'std_baseline': 4.409228906628326,
  'mean_event': 60.14519044393781,
  'std_event': 10.842733404193677,
  'value_at_ts': 66.10862100535425,
  'delta_at_ts': 25.67169843160047,
  'z_at_ts': 5.82226483932567,
  'delta_mean': 19.70826787018403,
  'z_shift': 4.469776527264641},
 {'detection_id': 1,
  'index': 738,
  'WT_ID': 15,
  're_at_ts': 1.219538331031799,
  'Date and time': '2022-09-04 04:10:00',
  'signal_name': 'Rotor bearing temp (°C)',
  'window_start': '2022-08-30 04:30:00',
  'window_end': '2022-09-09 04:30:00',
  'wind_center': 10.5,
  'n_baseline': 1531,
  'mean_baseline': 28.20605098772171,
  'std_baseline': 2.3350010539844988,
  'mean_event': 36.07045557250156,
  'std_event': 0.4192329641703486,
  'value_at_ts': 35.471666463216145,
  'delta_at_ts': 7.265615475494435,
  'z_at_ts': 3.11161121880276,
  'delta_mean': 7.864404584779848,
  'z_shift': 3.368051835077269},
 {'detection_id': 2,
  'index': 690,
  'WT_ID': 14,
  're_at_ts': 1.1518104076385498,
  'Date and time': '2021-06-25 09:00:00',
  'signal_name': 'Generator bearing front temperature (°C)',
  'window_start': '2021-06-20 06:30:00',
  'window_end': '2021-06-30 09:50:00',
  'wind_center': 15.5,
  'n_baseline': 657,
  'mean_baseline': 37.35763037648035,
  'std_baseline': 3.338454444193004,
  'mean_event': 44.63976004957114,
  'std_event': 2.6476845035543297,
  'value_at_ts': 43.0016663869222,
  'delta_at_ts': 5.644036010441852,
  'z_at_ts': 1.6906134574516172,
  'delta_mean': 7.282129673090786,
  'z_shift': 2.181287717062461},
 {'detection_id': 3,
  'index': 688,
  'WT_ID': 14,
  're_at_ts': 1.195350170135498,
  'Date and time': '2021-06-25 09:00:00',
  'signal_name': 'Rotor bearing temp (°C)',
  'window_start': '2021-06-20 06:30:00',
  'window_end': '2021-06-30 09:50:00',
  'wind_center': 15.5,
  'n_baseline': 657,
  'mean_baseline': 26.83720705292112,
  'std_baseline': 2.484277917647081,
  'mean_event': 32.101889020547105,
  'std_event': 0.4622551509190892,
  'value_at_ts': 31.60500036875408,
  'delta_at_ts': 4.767793315832964,
  'z_at_ts': 1.9191867713209212,
  'delta_mean': 5.2646819676259895,
  'z_shift': 2.119200082337122},
 {'detection_id': 4,
  'index': 550,
  'WT_ID': 12,
  're_at_ts': 0.907640278339386,
  'Date and time': '2020-10-10 19:00:00',
  'signal_name': 'Generator bearing front temperature (°C)',
  'window_start': '2020-10-05 15:50:00',
  'window_end': '2020-10-15 21:10:00',
  'wind_center': 11.5,
  'n_baseline': 1155,
  'mean_baseline': 37.90058144860884,
  'std_baseline': 4.653484808270166,
  'mean_event': 47.56226485839333,
  'std_event': 11.513257486918691,
  'value_at_ts': 68.94333419799804,
  'delta_at_ts': 31.0427527493892,
  'z_at_ts': 6.670861521718105,
  'delta_mean': 9.661683409784494,
  'z_shift': 2.076225411247452},
 {'detection_id': 5,
  'index': 633,
  'WT_ID': 13,
  're_at_ts': 0.0330195426940918,
  'Date and time': '2022-07-08 22:50:00',
  'signal_name': 'Nacelle temperature (°C)',
  'window_start': '2022-07-06 19:40:00',
  'window_end': '2022-07-16 19:50:00',
  'wind_center': 10.5,
  'n_baseline': 1863,
  'mean_baseline': 15.383856714668964,
  'std_baseline': 3.5245422065626046,
  'mean_event': 22.644531845577227,
  'std_event': 2.323672546194856,
  'value_at_ts': 18.99000002543132,
  'delta_at_ts': 3.6061433107623575,
  'z_at_ts': 1.023152256212967,
  'delta_mean': 7.260675130908263,
  'z_shift': 2.060033532124846},
 {'detection_id': 6,
  'index': 133,
  'WT_ID': 4,
  're_at_ts': 0.0255201142281293,
  'Date and time': '2022-07-04 06:50:00',
  'signal_name': 'Temp. top box (°C)',
  'window_start': '2022-06-29 06:50:00',
  'window_end': '2022-07-09 17:10:00',
  'wind_center': 12.5,
  'n_baseline': 1101,
  'mean_baseline': 19.56897775525657,
  'std_baseline': 3.115493678533062,
  'mean_event': 25.713479415209346,
  'std_event': 1.276692575237618,
  'value_at_ts': 25.186666488647443,
  'delta_at_ts': 5.617688733390871,
  'z_at_ts': 1.8031456048519328,
  'delta_mean': 6.144501659952773,
  'z_shift': 1.972240130766668},
 {'detection_id': 7,
  'index': 660,
  'WT_ID': 14,
  're_at_ts': 1.602267146110535,
  'Date and time': '2020-08-28 19:40:00',
  'signal_name': 'Rotor bearing temp (°C)',
  'window_start': '2020-08-23 18:20:00',
  'window_end': '2020-09-02 21:10:00',
  'wind_center': 12.5,
  'n_baseline': 1123,
  'mean_baseline': 26.79140506804701,
  'std_baseline': 2.569420401493873,
  'mean_event': 31.51547731263632,
  'std_event': 1.3255813836788424,
  'value_at_ts': 31.57115415426401,
  'delta_at_ts': 4.779749086217002,
  'z_at_ts': 1.860244078173441,
  'delta_mean': 4.724072244589312,
  'z_shift': 1.8385750505610967},
 {'detection_id': 8,
  'index': 181,
  'WT_ID': 5,
  're_at_ts': 0.6790734529495239,
  'Date and time': '2021-01-21 13:10:00',
  'signal_name': 'Generator bearing front temperature (°C)',
  'window_start': '2021-01-16 00:50:00',
  'window_end': '2021-01-26 14:40:00',
  'wind_center': 18.5,
  'n_baseline': 337,
  'mean_baseline': 35.0593863689911,
  'std_baseline': 4.889609150176876,
  'mean_event': 43.88508912381672,
  'std_event': 19.45181621557932,
  'value_at_ts': 57.81166674296061,
  'delta_at_ts': 22.752280373969512,
  'z_at_ts': 4.653189994367234,
  'delta_mean': 8.82570275482562,
  'z_shift': 1.8049914591857228},
 {'detection_id': 9,
  'index': 132,
  'WT_ID': 4,
  're_at_ts': 0.0258562974631786,
  'Date and time': '2022-07-04 06:50:00',
  'signal_name': 'Hub temperature (°C)',
  'window_start': '2022-06-29 06:50:00',
  'window_end': '2022-07-09 17:10:00',
  'wind_center': 12.5,
  'n_baseline': 1101,
  'mean_baseline': 16.64677984705424,
  'std_baseline': 2.765424924421488,
  'mean_event': 21.54485823678788,
  'std_event': 1.2719202420410407,
  'value_at_ts': 19.0,
  'delta_at_ts': 2.3532201529457595,
  'z_at_ts': 0.8509434236179964,
  'delta_mean': 4.898078389733637,
  'z_shift': 1.7711847269758334},
 {'detection_id': 10,
  'index': 131,
  'WT_ID': 4,
  're_at_ts': 0.0265682768076658,
  'Date and time': '2022-07-25 15:10:00',
  'signal_name': 'Hub temperature (°C)',
  'window_start': '2022-07-20 13:50:00',
  'window_end': '2022-07-30 15:10:00',
  'wind_center': 8.5,
  'n_baseline': 2540,
  'mean_baseline': 17.89047028790116,
  'std_baseline': 3.692256534646552,
  'mean_event': 23.95325049557196,
  'std_event': 1.0679941992316933,
  'value_at_ts': 22.0,
  'delta_at_ts': 4.1095297120988405,
  'z_at_ts': 1.1130130513784122,
  'delta_mean': 6.062780207670798,
  'z_shift': 1.6420257235054685},
 {'detection_id': 11,
  'index': 138,
  'WT_ID': 4,
  're_at_ts': 0.0130225736647844,
  'Date and time': '2022-07-25 15:10:00',
  'signal_name': 'Temp. top box (°C)',
  'window_start': '2022-07-20 13:50:00',
  'window_end': '2022-07-30 15:10:00',
  'wind_center': 8.5,
  'n_baseline': 2540,
  'mean_baseline': 23.59625295978549,
  'std_baseline': 2.936658091308173,
  'mean_event': 28.38115458225088,
  'std_event': 2.471935372810014,
  'value_at_ts': 24.995000076293945,
  'delta_at_ts': 1.3987471165084528,
  'z_at_ts': 0.4763057438141743,
  'delta_mean': 4.784901622465387,
  'z_shift': 1.6293696690900403},
 {'detection_id': 12,
  'index': 643,
  'WT_ID': 14,
  're_at_ts': 2.270829677581787,
  'Date and time': '2021-08-31 10:30:00',
  'signal_name': 'Rotor bearing temp (°C)',
  'window_start': '2021-08-25 02:50:00',
  'window_end': '2021-09-04 06:10:00',
  'wind_center': 7.5,
  'n_baseline': 4176,
  'mean_baseline': 27.845048425086947,
  'std_baseline': 3.048221339104272,
  'mean_event': 32.722076507755354,
  'std_event': 0.566941040959948,
  'value_at_ts': 31.97166633605957,
  'delta_at_ts': 4.126617910972623,
  'z_at_ts': 1.3537789589076366,
  'delta_mean': 4.877028082668407,
  'z_shift': 1.599958644768734},
 {'detection_id': 13,
  'index': 756,
  'WT_ID': 15,
  're_at_ts': 0.9207759499549866,
  'Date and time': '2022-09-04 04:10:00',
  'signal_name': 'Transformer cell temperature (°C)',
  'window_start': '2022-08-30 04:30:00',
  'window_end': '2022-09-09 04:30:00',
  'wind_center': 10.5,
  'n_baseline': 1531,
  'mean_baseline': 14.19943047958066,
  'std_baseline': 4.342676590780245,
  'mean_event': 20.98327428316924,
  'std_event': 0.8491413613897731,
  'value_at_ts': 20.251666450500487,
  'delta_at_ts': 6.052235970919828,
  'z_at_ts': 1.3936649078978334,
  'delta_mean': 6.7838438035885815,
  'z_shift': 1.5621342418155375},
 {'detection_id': 14,
  'index': 68,
  'WT_ID': 2,
  're_at_ts': 0.7160118818283081,
  'Date and time': '2021-01-21 12:30:00',
  'signal_name': 'Generator bearing rear temperature (°C)',
  'window_start': '2021-01-11 02:10:00',
  'window_end': '2021-01-26 15:10:00',
  'wind_center': 19.5,
  'n_baseline': 231,
  'mean_baseline': 43.69537190953712,
  'std_baseline': 3.3381338288846627,
  'mean_event': 48.72345403802806,
  'std_event': 9.817429998854944,
  'value_at_ts': 55.425862279431584,
  'delta_at_ts': 11.73049036989446,
  'z_at_ts': 3.514086304267152,
  'delta_mean': 5.0280821284909365,
  'z_shift': 1.5062554068333802},
 {'detection_id': 15,
  'index': 375,
  'WT_ID': 8,
  're_at_ts': 0.4076750576496124,
  'Date and time': '2022-05-09 04:30:00',
  'signal_name': 'Temperature motor axis 3 (°C)',
  'window_start': '2022-05-04 03:10:00',
  'window_end': '2022-05-14 03:10:00',
  'wind_center': 6.5,
  'n_baseline': 5279,
  'mean_baseline': 33.16793947533056,
  'std_baseline': 10.304646593539111,
  'mean_event': 47.66977636569072,
  'std_event': 13.950723848988552,
  'value_at_ts': 36.78499997456869,
  'delta_at_ts': 3.617060499238136,
  'z_at_ts': 0.3510125715040037,
  'delta_mean': 14.501836890360169,
  'z_shift': 1.4073104554068494},
 {'detection_id': 16,
  'index': 497,
  'WT_ID': 11,
  're_at_ts': 1.567467212677002,
  'Date and time': '2022-07-25 15:30:00',
  'signal_name': 'Rotor bearing temp (°C)',
  'window_start': '2022-07-20 14:00:00',
  'window_end': '2022-07-31 10:00:00',
  'wind_center': 5.5,
  'n_baseline': 5711,
  'mean_baseline': 29.484796384400884,
  'std_baseline': 3.1313810710402072,
  'mean_event': 33.789978198520224,
  'std_event': 2.4460930009065134,
  'value_at_ts': 36.05,
  'delta_at_ts': 6.565203615599113,
  'z_at_ts': 2.09658405242203,
  'delta_mean': 4.30518181411934,
  'z_shift': 1.3748508138899909},
 {'detection_id': 17,
  'index': 387,
  'WT_ID': 8,
  're_at_ts': 0.2410704940557479,
  'Date and time': '2022-07-25 10:10:00',
  'signal_name': 'Hub temperature (°C)',
  'window_start': '2022-07-20 11:50:00',
  'window_end': '2022-07-30 12:30:00',
  'wind_center': 7.5,
  'n_baseline': 4024,
  'mean_baseline': 18.583183647751856,
  'std_baseline': 3.61585973358898,
  'mean_event': 23.24216666666667,
  'std_event': 1.45009536993982,
  'value_at_ts': 22.0,
  'delta_at_ts': 3.4168163522481443,
  'z_at_ts': 0.944952681794636,
  'delta_mean': 4.658983018914814,
  'z_shift': 1.2884855503757235},
 {'detection_id': 18,
  'index': 416,
  'WT_ID': 9,
  're_at_ts': 0.7060006856918335,
  'Date and time': '2021-01-21 10:40:00',
  'signal_name': 'Gear oil temperature (°C)',
  'window_start': '2021-01-16 01:20:00',
  'window_end': '2021-01-26 14:20:00',
  'wind_center': 15.5,
  'n_baseline': 461,
  'mean_baseline': 56.50505278723587,
  'std_baseline': 1.0858593665061873,
  'mean_event': 57.87508731963143,
  'std_event': 1.5502164630452786,
  'value_at_ts': 55.1678570338658,
  'delta_at_ts': -1.337195753370068,
  'z_at_ts': -1.2314631108009588,
  'delta_mean': 1.3700345323955645,
  'z_shift': 1.2617053134640506},
 {'detection_id': 19,
  'index': 718,
  'WT_ID': 15,
  're_at_ts': 1.5681090354919434,
  'Date and time': '2021-10-31 07:50:00',
  'signal_name': 'Rotor bearing temp (°C)',
  'window_start': '2021-10-26 06:30:00',
  'window_end': '2021-11-05 09:10:00',
  'wind_center': 10.5,
  'n_baseline': 1531,
  'mean_baseline': 28.20605098772171,
  'std_baseline': 2.3350010539844988,
  'mean_event': 31.07799099855437,
  'std_event': 2.1454614313335,
  'value_at_ts': 29.17586221366094,
  'delta_at_ts': 0.9698112259392282,
  'z_at_ts': 0.4153365259875666,
  'delta_mean': 2.87194001083266,
  'z_shift': 1.229952340249233},
 {'detection_id': 20,
  'index': 408,
  'WT_ID': 8,
  're_at_ts': 0.0881740525364875,
  'Date and time': '2020-05-18 12:30:00',
  'signal_name': 'Temp. top box (°C)',
  'window_start': '2020-05-17 12:50:00',
  'window_end': '2020-05-27 16:50:00',
  'wind_center': 9.5,
  'n_baseline': 1677,
  'mean_baseline': 23.13000155553507,
  'std_baseline': 3.066232178918604,
  'mean_event': 26.85799624248655,
  'std_event': 2.062999937831104,
  'value_at_ts': 28.593103474584108,
  'delta_at_ts': 5.463101919049038,
  'z_at_ts': 1.7816987104269972,
  'delta_mean': 3.72799468695148,
  'z_shift': 1.2158227001147273},
 {'detection_id': 21,
  'index': 622,
  'WT_ID': 13,
  're_at_ts': 0.0864681974053382,
  'Date and time': '2022-06-19 22:50:00',
  'signal_name': 'Temp. top box (°C)',
  'window_start': '2022-06-12 23:10:00',
  'window_end': '2022-06-23 01:00:00',
  'wind_center': 9.5,
  'n_baseline': 2245,
  'mean_baseline': 23.193654784774875,
  'std_baseline': 2.920312660063487,
  'mean_event': 26.60152012390422,
  'std_event': 2.1906272670788947,
  'value_at_ts': 30.00833333333332,
  'delta_at_ts': 6.814678548558444,
  'z_at_ts': 2.333544158388265,
  'delta_mean': 3.4078653391293443,
  'z_shift': 1.1669522191008337},
 {'detection_id': 22,
  'index': 702,
  'WT_ID': 14,
  're_at_ts': 0.9275385737419128,
  'Date and time': '2021-06-25 09:00:00',
  'signal_name': 'Hub temperature (°C)',
  'window_start': '2021-06-20 06:30:00',
  'window_end': '2021-06-30 09:50:00',
  'wind_center': 15.5,
  'n_baseline': 657,
  'mean_baseline': 16.78722069072539,
  'std_baseline': 2.929374680964614,
  'mean_event': 20.180371787914865,
  'std_event': 1.3254826766919088,
  'value_at_ts': 18.883333333333333,
  'delta_at_ts': 2.0961126426079417,
  'z_at_ts': 0.7155495185469797,
  'delta_mean': 3.393151097189474,
  'z_shift': 1.1583192546991437},
 {'detection_id': 23,
  'index': 56,
  'WT_ID': 1,
  're_at_ts': 0.0368095822632312,
  'Date and time': '2022-06-09 16:20:00',
  'signal_name': 'Hub temperature (°C)',
  'window_start': '2022-06-04 15:00:00',
  'window_end': '2022-06-14 22:40:00',
  'wind_center': 10.5,
  'n_baseline': 1754,
  'mean_baseline': 16.56973840757544,
  'std_baseline': 3.160540534188495,
  'mean_event': 20.12065479259291,
  'std_event': 1.1632417083598652,
  'value_at_ts': 20.440666707356765,
  'delta_at_ts': 3.870928299781326,
  'z_at_ts': 1.2247678072495378,
  'delta_mean': 3.550916385017469,
  'z_shift': 1.1235155336899385},
 {'detection_id': 24,
  'index': 638,
  'WT_ID': 13,
  're_at_ts': 0.017876936122775,
  'Date and time': '2022-06-19 22:50:00',
  'signal_name': 'Hub temperature (°C)',
  'window_start': '2022-06-12 23:10:00',
  'window_end': '2022-06-23 01:00:00',
  'wind_center': 9.5,
  'n_baseline': 2245,
  'mean_baseline': 19.078736458480137,
  'std_baseline': 3.39350928865565,
  'mean_event': 22.880403060488774,
  'std_event': 2.2161798170903118,
  'value_at_ts': 21.0,
  'delta_at_ts': 1.9212635415198636,
  'z_at_ts': 0.5661583269987095,
  'delta_mean': 3.801666602008641,
  'z_shift': 1.1202758792255094},
 {'detection_id': 25,
  'index': 720,
  'WT_ID': 15,
  're_at_ts': 1.5318098068237305,
  'Date and time': '2021-05-23 22:50:00',
  'signal_name': 'Rotor bearing temp (°C)',
  'window_start': '2021-05-18 22:10:00',
  'window_end': '2021-05-28 23:40:00',
  'wind_center': 10.5,
  'n_baseline': 1531,
  'mean_baseline': 28.20605098772171,
  'std_baseline': 2.3350010539844988,
  'mean_event': 30.775805622582364,
  'std_event': 1.1697455340973706,
  'value_at_ts': 30.611667378743498,
  'delta_at_ts': 2.405616391021788,
  'z_at_ts': 1.0302421007120273,
  'delta_mean': 2.5697546348606544,
  'z_shift': 1.100536820090752},
 {'detection_id': 26,
  'index': 147,
  'WT_ID': 5,
  're_at_ts': 1.7432326078414917,
  'Date and time': '2022-09-10 05:00:00',
  'signal_name': 'Rotor bearing temp (°C)',
  'window_start': '2022-09-05 03:40:00',
  'window_end': '2022-09-15 06:30:00',
  'wind_center': 7.5,
  'n_baseline': 4215,
  'mean_baseline': 28.97200314649649,
  'std_baseline': 3.786173224427557,
  'mean_event': 32.98960429178909,
  'std_event': 1.2319889232487509,
  'value_at_ts': 33.493333307902006,
  'delta_at_ts': 4.521330161405512,
  'z_at_ts': 1.194168859532069,
  'delta_mean': 4.017601145292598,
  'z_shift': 1.0611244935577482},
 {'detection_id': 27,
  'index': 317,
  'WT_ID': 7,
  're_at_ts': 0.2226953655481338,
  'Date and time': '2022-06-11 02:10:00',
  'signal_name': 'Transformer cell temperature (°C)',
  'window_start': '2022-06-06 01:20:00',
  'window_end': '2022-06-16 15:30:00',
  'wind_center': 10.5,
  'n_baseline': 1629,
  'mean_baseline': 14.996106468372176,
  'std_baseline': 4.043682073807921,
  'mean_event': 19.226912390490924,
  'std_event': 1.9247720336064635,
  'value_at_ts': 18.89333330790201,
  'delta_at_ts': 3.897226839529836,
  'z_at_ts': 0.9637817138922178,
  'delta_mean': 4.230805922118748,
  'z_shift': 1.046275608441841},
 {'detection_id': 28,
  'index': 684,
  'WT_ID': 14,
  're_at_ts': 1.2271775007247925,
  'Date and time': '2020-08-28 19:40:00',
  'signal_name': 'Nacelle temperature (°C)',
  'window_start': '2020-08-23 18:20:00',
  'window_end': '2020-09-02 21:10:00',
  'wind_center': 12.5,
  'n_baseline': 1123,
  'mean_baseline': 13.171243221595429,
  'std_baseline': 3.401800606791981,
  'mean_event': 16.687533150804366,
  'std_event': 1.4411421143691123,
  'value_at_ts': 16.492307809683002,
  'delta_at_ts': 3.321064588087575,
  'z_at_ts': 0.9762666810796584,
  'delta_mean': 3.51628992920894,
  'z_shift': 1.0336555064951105},
 {'detection_id': 29,
  'index': 682,
  'WT_ID': 14,
  're_at_ts': 1.2308157682418823,
  'Date and time': '2020-08-28 19:40:00',
  'signal_name': 'Hub temperature (°C)',
  'window_start': '2020-08-23 18:20:00',
  'window_end': '2020-09-02 21:10:00',
  'wind_center': 12.5,
  'n_baseline': 1123,
  'mean_baseline': 17.034011562137586,
  'std_baseline': 2.938013605912265,
  'mean_event': 20.0139306300779,
  'std_event': 1.4844699017283542,
  'value_at_ts': 19.0,
  'delta_at_ts': 1.9659884378624144,
  'z_at_ts': 0.6691556614667095,
  'delta_mean': 2.979919067940316,
  'z_shift': 1.0142631953588377},
 {'detection_id': 30,
  'index': 141,
  'WT_ID': 5,
  're_at_ts': 2.2295026779174805,
  'Date and time': '2022-09-10 05:00:00',
  'signal_name': 'Transformer cell temperature (°C)',
  'window_start': '2022-09-05 03:40:00',
  'window_end': '2022-09-15 06:30:00',
  'wind_center': 7.5,
  'n_baseline': 4215,
  'mean_baseline': 14.78459289597034,
  'std_baseline': 5.03160354332223,
  'mean_event': 19.838755160245725,
  'std_event': 1.7846387314243206,
  'value_at_ts': 20.743333307902017,
  'delta_at_ts': 5.958740411931675,
  'z_at_ts': 1.1842627028593913,
  'delta_mean': 5.054162264275384,
  'z_shift': 1.0044834058881869},
 {'detection_id': 31,
  'index': 647,
  'WT_ID': 14,
  're_at_ts': 2.016151666641236,
  'Date and time': '2020-08-28 19:40:00',
  'signal_name': 'Transformer cell temperature (°C)',
  'window_start': '2020-08-23 18:20:00',
  'window_end': '2020-09-02 21:10:00',
  'wind_center': 12.5,
  'n_baseline': 1123,
  'mean_baseline': 15.385827440701334,
  'std_baseline': 4.072421560417742,
  'mean_event': 19.44600093828508,
  'std_event': 1.6818772037998897,
  'value_at_ts': 19.56923132676345,
  'delta_at_ts': 4.183403886062116,
  'z_at_ts': 1.0272521702377468,
  'delta_mean': 4.060173497583747,
  'z_shift': 0.9969924373858932},
 {'detection_id': 32,
  'index': 420,
  'WT_ID': 9,
  're_at_ts': 0.5390337705612183,
  'Date and time': '2020-10-10 18:30:00',
  'signal_name': 'Gear oil inlet temperature (°C)',
  'window_start': '2020-10-05 15:30:00',
  'window_end': '2020-10-15 22:10:00',
  'wind_center': 9.5,

In [37]:
from directory_tree import DisplayTree

DisplayTree('.')

/
├── __init__.py
├── __pycache__/
│   ├── __init__.cpython-312.pyc
│   └── data_setup.cpython-312.pyc
├── data_setup.py
├── data_test.ipynb
├── detections/
│   └── catalog.csv
├── raw_signals/
│   ├── WT_1.csv
│   ├── WT_10.csv
│   ├── WT_11.csv
│   ├── WT_12.csv
│   ├── WT_13.csv
│   ├── WT_14.csv
│   ├── WT_15.csv
│   ├── WT_2.csv
│   ├── WT_4.csv
│   ├── WT_5.csv
│   ├── WT_6.csv
│   ├── WT_7.csv
│   ├── WT_8.csv
│   └── WT_9.csv
└── status_logs/
    ├── Status_Logs_Complete_ID_1.csv
    ├── Status_Logs_Complete_ID_10.csv
    ├── Status_Logs_Complete_ID_11.csv
    ├── Status_Logs_Complete_ID_12.csv
    ├── Status_Logs_Complete_ID_13.csv
    ├── Status_Logs_Complete_ID_14.csv
    ├── Status_Logs_Complete_ID_15.csv
    ├── Status_Logs_Complete_ID_2.csv
    ├── Status_Logs_Complete_ID_4.csv
    ├── Status_Logs_Complete_ID_5.csv
    ├── Status_Logs_Complete_ID_6.csv
    ├── Status_Logs_Complete_ID_7.csv
    ├── Status_Logs_Complete_ID_8.csv
    └── Status_Logs_Complete_ID_9.csv

In [16]:


pc_df.tail()

                  Power (kW)
Wind speed (m/s)
23.0                  2050.0
23.5                  2050.0
24.0                  2050.0
24.5                  2050.0
25.0                  2050.0

In [35]:
import numpy as np
pc_interpol_df = pd.DataFrame(index=[np.round(i,2) for i in np.arange(0,30, 0.01)], columns=["power_norm"])

pc_interpol_df.head()

     power_norm
0.00        NaN
0.01        NaN
0.02        NaN
0.03        NaN
0.04        NaN

In [36]:

def create_powercurve():
    pc_path = list(cts.PATH_POWERCURVE.glob("*.csv"))[0]
    pc_df = pd.read_csv(pc_path, index_col=0)
    pc_interpol_df = pd.DataFrame(index=[np.round(i,2) for i in np.arange(0,30, 0.1)], columns=["power_norm"])
    
    pc_interpol_df[pc_interpol_df.index < pc_df.index[0]] = 0
    pc_interpol_df[pc_interpol_df.index > pc_df.index[-1]] = 0
    pc_interpol_df.loc[pc_df.index] = pc_df.values.reshape(-1,1)
    pc_interpol_df = pc_interpol_df.astype(float).interpolate(method="linear")
    
    pc_interpol_df.to_csv(cts.PATH_POWERCURVE/"pc_interpol.csv")

create_powercurve()

In [37]:
df_pc = pd.read_csv(cts.PATH_POWERCURVE/"pc_interpol.csv").rename(columns={"Unnamed: 0": "Wind Speed (m/s)"})
print(df_pc.columns)
list_pc = list(df_pc.values.reshape(-1,2))

list_pc[-1]

Index(['Wind Speed (m/s)', 'power_norm'], dtype='str')

array([29.9,  0. ])

In [42]:
type(list_pc)

list

In [26]:
def get_data_for_pc( wt_id: str, window_half_size: int, det_ts: str):
    file = list(cts.PATH_SIGNALS.glob(f"WT_{wt_id}.csv"))[0]
    wt_df = pd.read_csv(file)
    wt_df = wt_df[["Wind speed (m/s)", "Power (kW)", cts.DET_TS_COL, cts.WT_ID]]
    det_ts = pd.to_datetime(det_ts)
    delta = pd.Timedelta(hours=window_half_size)
    wt_df[cts.DET_TS_COL] = pd.to_datetime(wt_df[cts.DET_TS_COL])
    mask = wt_df[cts.DET_TS_COL].between(det_ts -delta , det_ts+delta)
    wt_df = wt_df[mask].round(2)
    wt_df = wt_df[["Wind speed (m/s)", "Power (kW)"]]
    points = list(wt_df.values.reshape(-1,2).tolist())
    return points

In [27]:
import pprint
points = get_data_for_pc("2", window_half_size=1, det_ts="2021-01-21 12:30:00")

pprint.pp(points)
print(type(points))

[[22.42, 2051.87],
 [20.34, 2053.24],
 [19.09, 2040.9],
 [19.93, 2043.7],
 [19.93, 2033.13],
 [20.49, 2038.75],
 [19.79, 2063.26],
 [19.02, 2035.97],
 [18.01, 2002.75],
 [18.68, 2048.71],
 [19.18, 2014.24],
 [18.52, 2049.31],
 [17.86, 2028.29]]
<class 'list'>

C:\Users\admin\AppData\Local\Temp\ipykernel_13444\980341280.py:9: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  wt_df = wt_df[mask].round(2)