In [ ]:
from pathlib import Path
import sys
sys.path.insert(0, str(Path.cwd().parent))
from src import constants as cts
from src import helper as hp
import pandas as pd
from dotenv import load_dotenv
load_dotenv()
from google import genai
from src import reviewer
from src.llm import LLMProvider
from src.providers import penmanshiel_provider as pp
import examples.data_setup as ds
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None) 
pd.set_option("display.width", None)

In [ ]:
ds.penmanshiel_setup()

In [ ]:
log_path = list(Path(cts.PATH_STATUS_LOGS).glob("*.csv"))

[WindowsPath('status_logs/Status_Logs_Complete_ID_1.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_10.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_11.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_12.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_13.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_14.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_15.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_2.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_4.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_5.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_6.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_7.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_8.csv'), WindowsPath('status_logs/Status_Logs_Complete_ID_9.csv')]

C:\Users\admin\AppData\Local\Temp\ipykernel_15480\495428329.py:4: DtypeWarning: Columns (0: Comment) have mixed types. Specify dtype option on import or set low_memory=False.
  log1 = pd.read_csv(log_path[0])

,Timestamp start,Timestamp end,Duration,Status,Code,Message,Comment,Service contract category,IEC category,WT_ID,Global contract category,Custom contract category
0,2016-06-06 17:08:40,2016-06-10 11:28:00,90:19:20,Stop,3500,Grid loss,NaN,External stop (grid) (4),Out of Electrical Specification,1,NaN,NaN
1,2016-06-06 17:08:41,2016-06-06 18:14:07,01:05:26,Warning,3875,Overload transf. fan inlet air,NaN,Warnings (27),NaN,1,NaN,NaN
2,2016-06-06 17:08:41,2016-06-06 18:14:39,01:05:58,Warning,1825,Overload gear bypass filter,NaN,Warnings (27),NaN,1,NaN,NaN
3,2016-06-06 17:08:41,2016-06-06 18:14:07,01:05:26,Warning,3875,Overload transf. fan inlet air,NaN,Warnings (27),NaN,1,NaN,NaN
4,2016-06-06 17:08:41,2016-06-06 18:14:39,01:05:58,Warning,1825,Overload gear bypass filter,NaN,Warnings (27),NaN,1,NaN,NaN

In [ ]:
client = genai.Client()

for model in client.models.list():
    print(model.name)
    print("supported actions:", model.supported_actions)
    print()

models/gemini-2.5-flash
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.5-pro
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.0-flash
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.0-flash-001
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.0-flash-lite-001
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.0-flash-lite
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.5-flash-preview-tts
supported actions: ['countTokens', 'generateContent']

models/gemini-2.5-pro-preview-tts
supported actions: ['countTokens', 'generateContent', 'batchGenerateContent']

models/gemma-4-26b-a4b-it
supported actions: ['generateContent', 'countTokens']

models/gemma-4-31b-it
supported actions: ['generateContent', 'countTokens']

models/gemini-flash-latest
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-flash-lite-latest
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-pro-latest
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.5-flash-lite
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.5-flash-image
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-3-pro-preview
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3-flash-preview
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3.1-pro-preview
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3.1-pro-preview-customtools
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3.1-flash-lite-preview
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3.1-flash-lite
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-3-pro-image-preview
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-3-pro-image
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/nano-banana-pro-preview
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-3.1-flash-image-preview
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-3.1-flash-image
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-3.5-flash
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/lyria-3-clip-preview
supported actions: ['generateContent', 'countTokens']

models/lyria-3-pro-preview
supported actions: ['generateContent', 'countTokens']

models/gemini-3.1-flash-tts-preview
supported actions: ['generateContent', 'countTokens', 'batchGenerateContent']

models/gemini-robotics-er-1.5-preview
supported actions: ['generateContent', 'countTokens']

models/gemini-robotics-er-1.6-preview
supported actions: ['generateContent', 'countTokens', 'createCachedContent', 'batchGenerateContent']

models/gemini-2.5-computer-use-preview-10-2025
supported actions: ['generateContent', 'countTokens']

models/antigravity-preview-05-2026
supported actions: ['generateContent', 'countTokens']

models/deep-research-max-preview-04-2026
supported actions: ['generateContent', 'countTokens']

models/deep-research-preview-04-2026
supported actions: ['generateContent', 'countTokens']

models/deep-research-pro-preview-12-2025
supported actions: ['generateContent', 'countTokens']

models/gemini-embedding-001
supported actions: ['embedContent', 'countTextTokens', 'countTokens', 'asyncBatchEmbedContent']

models/gemini-embedding-2-preview
supported actions: ['embedContent', 'countTextTokens', 'countTokens', 'asyncBatchEmbedContent']

models/gemini-embedding-2
supported actions: ['embedContent', 'countTextTokens', 'countTokens', 'asyncBatchEmbedContent']

models/aqa
supported actions: ['generateAnswer']

models/imagen-4.0-generate-001
supported actions: ['predict']

models/imagen-4.0-ultra-generate-001
supported actions: ['predict']

models/imagen-4.0-fast-generate-001
supported actions: ['predict']

models/veo-2.0-generate-001
supported actions: ['predictLongRunning']

models/veo-3.0-generate-001
supported actions: ['predictLongRunning']

models/veo-3.0-fast-generate-001
supported actions: ['predictLongRunning']

models/veo-3.1-generate-preview
supported actions: ['predictLongRunning']

models/veo-3.1-fast-generate-preview
supported actions: ['predictLongRunning']

models/veo-3.1-lite-generate-preview
supported actions: ['predictLongRunning']

models/gemini-2.5-flash-native-audio-latest
supported actions: ['countTokens', 'bidiGenerateContent']

models/gemini-2.5-flash-native-audio-preview-09-2025
supported actions: ['countTokens', 'bidiGenerateContent']

models/gemini-2.5-flash-native-audio-preview-12-2025
supported actions: ['countTokens', 'bidiGenerateContent']

models/gemini-3.1-flash-live-preview
supported actions: ['bidiGenerateContent']

models/gemini-3.5-live-translate-preview
supported actions: ['bidiGenerateContent']

In [13]:
#test = dets.iloc[:5]
test = pp.penmanshielProvider()._load_detections()

outputs = reviewer.deep_search(
    detections=test,
    log_path=log_path,
    provider=LLMProvider.GEMINI,
    model="gemini-2.5-flash")

Inspecting Detections: 0it [00:00, ?it/s]

Inspecting Detections: 39it [43:31, 55.75s/it]c:\Users\admin\Programming\llms\llm-wind-turbine-status-log-review\src\helper.py:22: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[ts_cols[1]] = pd.to_datetime(df[ts_cols[1]], errors="coerce")
Inspecting Detections: 46it [51:13, 62.49s/it]c:\Users\admin\Programming\llms\llm-wind-turbine-status-log-review\src\reviewer.py:184: UserWarning: Error at detection idx=46
attempt=1, max retries=3
Exc. Msg: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
  warnings.warn(f"Error at detection idx={idx}\n"
c:\Users\admin\Programming\llms\llm-wind-turbine-status-log-review\src\reviewer.py:184: UserWarning: Error at detection idx=46
attempt=2, max retries=3
Exc. Msg: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
  warnings.warn(f"Error at detection idx={idx}\n"
c:\Users\admin\Programming\llms\llm-wind-turbine-status-log-review\src\reviewer.py:184: UserWarning: Error at detection idx=46
attempt=3, max retries=3
Exc. Msg: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
  warnings.warn(f"Error at detection idx={idx}\n"
c:\Users\admin\Programming\llms\llm-wind-turbine-status-log-review\src\reviewer.py:184: UserWarning: Error at detection idx=46
attempt=4, max retries=3
Exc. Msg: 503 UNAVAILABLE. {'error': {'code': 503, 'message': 'This model is currently experiencing high demand. Spikes in demand are usually temporary. Please try again later.', 'status': 'UNAVAILABLE'}}
  warnings.warn(f"Error at detection idx={idx}\n"
c:\Users\admin\Programming\llms\llm-wind-turbine-status-log-review\src\reviewer.py:189: UserWarning: Deep search stopped at idx=46
Restart later to continue from this detection.

  warnings.warn(f"Deep search stopped at idx={idx}\n"
Inspecting Detections: 46it [57:27, 74.95s/it]

In [14]:
try:
    if outputs:
        result_no_logs = pd.DataFrame([output.model_dump() for output in outputs if not output.relevant_logs])

        result_no_logs.head()
except:
    pass

In [ ]:
result = pd.DataFrame([output.model_dump() for output in outputs])

result.head()

,wt_id,detection_id,detection_index,detection_ts,relevant_signal,anomaly_description_reasoning,relevant_logs,overall_assessment,overall_reasoning
0,2,0,69,2021-01-21 12:30:00,Generator bearing front temperature (°C),"The generator bearing front temperature shows a significant increase, indicating a potential overheating issue.","[{'log_index': '64234', 'log_start_ts': '2021-01-18 11:04:27', 'log_end_ts': '2021-01-18 17:06:53', 'reasoning': 'Overload warnings for generator fans indicate a problem with the generator's cooling system, which can directly lead to increased generator bearing temperatures.'}, {'log_index': '64235', 'log_start_ts': '2021-01-18 11:04:27', 'log_end_ts': '2021-01-18 17:06:53', 'reasoning': 'Overload warnings for generator fans indicate a problem with the generator's cooling system, which can directly lead to increased generator bearing temperatures.'}, {'log_index': '64236', 'log_start_ts': '2021-01-18 11:04:27', 'log_end_ts': '2021-01-18 17:06:52', 'reasoning': 'Overload warnings for generator fans indicate a problem with the generator's cooling system, which can directly lead to increased generator bearing temperatures.'}]",possibly_undocumented_anomaly,"The anomaly statistics show a clear deviation in generator bearing front temperature, but no relevant status logs are found to document this event."