In [1]:
import os
import pandas as pd
from pathlib import Path

In [2]:
det_path = list(Path("detections").glob("*.csv"))

dets = pd.read_csv(det_path[0])

In [3]:
dets = dets[dets["z_shift"] > 0]
print(len(dets))
dets.head()

176

,WT_ID,re_at_ts,Date and time,signal_name,window_start,window_end,wind_center,n_baseline,mean_baseline,std_baseline,mean_event,std_event,value_at_ts,delta_at_ts,z_at_ts,delta_mean,z_shift
0,1,0.835527,2020-11-22 20:00:00,Temperature motor axis 1 (°C),2020-11-17 18:40:00,2020-11-27 21:20:00,10.5,1754,64.497127,10.605588,67.482501,8.585641,70.552414,6.055287,0.570952,2.985374,0.281491
1,1,0.827930,2020-11-22 20:00:00,Temperature motor axis 2 (°C),2020-11-17 18:40:00,2020-11-27 21:20:00,10.5,1754,67.582424,10.188067,70.793128,8.383787,75.880000,8.297575,0.814441,3.210703,0.315143
43,1,0.071285,2022-06-09 16:20:00,Temperature motor axis 3 (°C),2022-06-04 15:10:00,2022-06-14 22:30:00,10.5,1754,65.309504,10.562974,69.974042,9.523647,69.441379,4.131875,0.391166,4.664538,0.441593
44,1,0.070254,2022-06-09 16:20:00,Temperature motor axis 2 (°C),2022-06-04 15:10:00,2022-06-14 22:30:00,10.5,1754,67.582424,10.188067,70.668585,8.985749,72.615517,5.033093,0.494018,3.086161,0.302919
45,1,0.067432,2022-06-09 16:20:00,Temperature motor axis 1 (°C),2022-06-04 15:10:00,2022-06-14 22:30:00,10.5,1754,64.497127,10.605588,68.476585,9.285614,68.533000,4.035873,0.380542,3.979458,0.375223

In [4]:
log_path = list(Path("status_logs").glob("*.csv"))

#print(log_path)
log1 = pd.read_csv(log_path[0])
log1.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_10784\3447777767.py:4: DtypeWarning: Columns (0: Comment) have mixed types. Specify dtype option on import or set low_memory=False.
  log1 = pd.read_csv(log_path[0])

,Timestamp start,Timestamp end,Duration,Status,Code,Message,Comment,Service contract category,IEC category,WT_ID,Global contract category,Custom contract category
0,2016-06-06 17:08:40,2016-06-10 11:28:00,90:19:20,Stop,3500,Grid loss,NaN,External stop (grid) (4),Out of Electrical Specification,1,NaN,NaN
1,2016-06-06 17:08:41,2016-06-06 18:14:07,01:05:26,Warning,3875,Overload transf. fan inlet air,NaN,Warnings (27),NaN,1,NaN,NaN
2,2016-06-06 17:08:41,2016-06-06 18:14:39,01:05:58,Warning,1825,Overload gear bypass filter,NaN,Warnings (27),NaN,1,NaN,NaN
3,2016-06-06 17:08:41,2016-06-06 18:14:07,01:05:26,Warning,3875,Overload transf. fan inlet air,NaN,Warnings (27),NaN,1,NaN,NaN
4,2016-06-06 17:08:41,2016-06-06 18:14:39,01:05:58,Warning,1825,Overload gear bypass filter,NaN,Warnings (27),NaN,1,NaN,NaN

In [5]:
ts = pd.Timestamp("2020-11-22 20:00:00")
d = pd.Timedelta(days=30)

start = ts - d
print(start)

2020-10-23 20:00:00

In [6]:
from typing import Optional
from joblib import Parallel, delayed
def load_logfile(path:Path, wt_id: str, detection_ts: pd.Timestamp, delta_time: pd.Timedelta, wt_col: Optional[str]) -> pd.DataFrame:
    files = list(path.glob(".csv"))
    files = [fn for fn in files if wt_id in fn]
    
    if files:
        dfs = pd.concat([pd.read_csv(fn) for fn in files], axis=1)

In [7]:
files = []

if files:
    print("hi")